package org.scala_lang.virtualized

import scala.reflect.macros.blackbox.Context
import scala.language.experimental.macros

/** A SourceContext is a descriptor for the invocation of a method that takes
 *  an implicit parameter of type SourceContext. It provides information about the
 *  location in the source where the method is invoked, such as the source file name
 *  and line number.
 */
trait SourceContext extends SourceLocation {

  var parent: Option[SourceContext] = None

  def update(context: SourceContext): SourceContext

  def bindings: List[(String, Int)]

  def assignedVariable: Option[String] =
    if (bindings(0)._1 == null) None //TODO should this rather be "bindings == Nil"?
    else Some(bindings(0)._1)

  def methodName: String

  def receiver: Option[String]

  def allContexts: List[List[(String, Int)]]

  override def toString = if (SourceContext.debug) {
    "SourceContext at " + methodName + ":\n// " +
    "Assigning to: " + assignedVariable + "\n// " +
    "SourceLocation: " + super.toString + "\n// " +
    "Parent: " +
    (if (parent.isEmpty) "None" else "\n// " + parent.get.toString)
  } else
    super.toString
}

//using the available information from the macro Context, rebuild the SourceContext previously generated by the compiler
class SourceContextMacro(val c: Context) {
  import c.universe._
  def impl: c.Expr[SourceContext] = {
    import c.universe._
    val pos = c.enclosingPosition //pos.source.file.name, pos.source.getClass.getName
    val filename = pos.source.file.name//e.g. /Users/cedricbastin/folders/03-uni/00-class/MA5-PPL/virtualization-lms-core/test-src/epfl/test1-arith/TestNumeric.scala
    val line = pos.line
    val charOffset = pos.column
    val methodName = "DontKnow" //pos.getClass.getMethods
    //val receiver = Some(impli) //  implicit def impli(i:Int) = new OpsCls(i)
    val bindings = List(("todo: sourceInfo",line)) //aka: sourceInfo
    c.Expr( q"""SourceContext($filename, $methodName, $bindings)""")
  }
}

object SourceContext {

  var debug = false

  implicit def m: SourceContext = macro SourceContextMacro.impl

  def apply(name: String, sourceInfo: List[(String, Int)]): SourceContext =
    apply("<unknown file>", name, sourceInfo)

  def apply(fileName: String, name: String, sourceInfo: List[(String, Int)]): SourceContext =
    new ConcreteSourceContext(fileName, name, sourceInfo)

  def apply(fileName: String, name: String, receiver: String, sourceInfo: List[(String, Int)]): SourceContext =
    new ConcreteSourceContext(fileName, name, Some(receiver), sourceInfo)

  private class ConcreteSourceContext(override val fileName: String,
                                      val methodName: String,
                                      val receiver: Option[String],
                                      val bindings: List[(String, Int)])
  extends SourceContext {

    def this(file: String, method: String, bs: List[(String, Int)]) =
      this(file, method, None, bs)

    def line = bindings(0)._2

    def update(context: SourceContext): SourceContext = {
      context.parent = Some(this)
      context
    }

    def allContexts = {
      var contexts: List[List[(String, Int)]] = List()
      var curr: SourceContext = this
      contexts = contexts ::: List(curr.bindings)
      while (!curr.parent.isEmpty) {
        curr = curr.parent.get
        contexts = contexts ::: List(curr.bindings)
      }
      contexts
    }
  }
}